# Étape 1 : Builder l'application en mode développement
FROM node:23-alpine3.20 AS dev

WORKDIR /app

# Copier les fichiers package.json et yarn.lock en premier pour optimiser le cache
COPY package.json yarn.lock ./

# Installer les dépendances sans suppression des node_modules
RUN yarn install

# Copier tout le reste
COPY . .

# Ajouter un volume pour que les modifications locales soient reflétées
VOLUME [ "/app" ]

EXPOSE 3000

# Lancer l'application en mode développement
CMD ["yarn", "start"]
