services:
  server:
    build:
      context: server/
      dockerfile: Dockerfile.prod
    ports:
      - "3001:3001"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

    depends_on:
      - database
    networks:
      - database-network

  client:
    build:
      context: client/
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    depends_on:
      - server


  database:
    image: "postgres:17.1-alpine"
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - database-network

volumes:
  server-data:

networks:
  database-network:
