version: "3.9"

services:
  server:
    build:
      context: server/
      dockerfile: Dockerfile.dev
    env_file:
      - .env.prod
    ports:
      - "3001:3001"
    depends_on:
      - database
    networks:
      - database-network
      - mailcatcher-network
    develop:
      watch:
        - action: sync
          path: ./server/src
          target: /app/src
          ignore:
            - node_modules/

  client:
    build:
      context: client/
      dockerfile: Dockerfile.dev
    ports:
        - "3000:3000"
    depends_on:
      - server
    develop:
      watch:
        - action: sync
          path: ./client/src
          target: /app/src
          ignore:
            - node_modules/



  mailcatcher:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - mailcatcher-network

  database:
    image: "postgres:17.1-alpine"
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - database-network

  admin:
      image: dpage/pgadmin4:latest
      environment:
        PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
        PGADMIN_DEFAULT_PASSWORD: "admin"
      ports:
        - "8080:80"
      networks:
        - database-network

volumes:
  database-data:

networks:
  database-network:
    driver: bridge
  mailcatcher-network:
    driver: bridge

