services:
  server:
    build: back/.
    env_file:
      - .env.prod
    ports:
      - "3001:3001"
    depends_on:
      - database
    networks:
      - database-network

  database:
    image: "postgres:17.1-alpine"
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - database-network

volumes:
  server-data:

networks:
  database-network:
