FROM node:23-alpine3.20

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Copy application code
COPY . .

COPY .env.prod .env

EXPOSE 3001

CMD ["yarn", "startQuiet"]
