FROM node:23-alpine3.20

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

COPY .env.prod .env

EXPOSE 3001

# Command to start the application
CMD ["yarn", "start"]
